### ISSUE TITLE
How to specify data nodes?

### ISSUE THREAD

**Issue by srbhklkrn** [saravanan30erd/opendistro_standalone_installation#6]
I want to set up a 7 node elastic cluster out of 7, 4 will be data nodes and 3 will be master nodes, is there any property where I can specify that?

**Comment by saravanan30erd** [comment]
@srbhklkrn   I tried to add the functionality to configure the nodes with specific roles. 

Noticed there is major change in latest elastic-search version 7.9 (https://www.elastic.co/guide/en/elasticsearch/reference/7.9/modules-node.html)

We need to configure nodes roles as below in 7.9
```
node.roles: [ data, master]
```

But this script uses elastic-search version 7.8, since [opendistro](https://opendistro.github.io/for-elasticsearch-docs/version-history/) didn't release the plugins for elasticsearch 7.9.

Current ES 7.8 uses nodes settings as below,
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/modules-node.html
```
node.master: true 
node.data: false 
```

so I will add this functionality, once opendistro release plugins for ES 7.9 version.

**Comment by srbhklkrn** [comment]
Sure, will this playbook works with Ubuntu?

**Comment by saravanan30erd** [comment]
Unfortunately this script will only support Centos 7 & RHEL 7.

**Comment by saravanan30erd** [comment]
@srbhklkrn 

Now you can mention the ES node roles details using `roles` parameter in hosts inventory file `inventories/opendistro/hosts`.

example,

es1 ansible_host=10.0.1.1 ip=10.0.1.1 roles=master
es2 ansible_host=10.0.1.2 ip=10.0.1.2 roles=master
es3 ansible_host=10.0.1.3 ip=10.0.1.3 roles=master
es4 ansible_host=10.0.1.4 ip=10.0.1.4 roles=data,ingest
es5 ansible_host=10.0.1.5 ip=10.0.1.5 roles=data,ingest
es6 ansible_host=10.0.1.6 ip=10.0.1.6 roles=data
es7 ansible_host=10.0.1.7 ip=10.0.1.5 roles=data
